import re,os,sys,json,pathlib
# D-38: search and link-preview tags MUST carry the full address (crawlers
# cannot resolve a relative one). They are metadata, not navigation. Strip
# exactly those tags before the "no hard-coded origin" checks, which still
# cover every link and script.
def _nometa(t):
    return re.sub(r'<(link rel="canonical"|meta property="og:(url|image)"|meta name="twitter:image")[^>]*>', '', t)
# Anchor every path to THIS file so the suite runs from any CWD.
ROOT=pathlib.Path(__file__).resolve().parent
os.chdir(ROOT)
F=[]
def ck(l,c,x=''):
    print(('  PASS  ' if c else '  FAIL  ')+l+(('  ['+x+']') if x else ''))
    if not c: F.append(l)
g=open('FLUX-Sparta/public/index.html',encoding='utf-8').read()
h=open('FLUX-Sparta/public/hero-demo.html',encoding='utf-8').read()
p=open('FLUX-Sparta/public/play/index.html',encoding='utf-8').read()
for fn,s in [('FLUX-Sparta/public/index.html',g),('FLUX-Sparta/public/hero-demo.html',h),('FLUX-Sparta/public/play/index.html',p)]:
    b=re.findall(r'<script\b[^>]*>(.*?)</script>',s,re.S)
    ck(fn+' no stray </script>', not any('</script' in x for x in b))
    ck(fn+' closes body/html', '</body>' in s and '</html>' in s)
print('\n--- Phase 1 baseline ---')
ck('XSS player name escaped', "escapeHtml2(p.name||'PILOT')" in g)
ck('sorting numeric', g.count('b.totalScore-a.totalScore')==2 and 'b.score-a.score' in g)
ck('no secrets', not any(k in g+h+p for k in ['sk_live','sk_test','whsec_']))
ck('no stale dev URLs', not any(k in g+h+p for k in ['localhost','127.0.0.1','.pages.dev']))
ck('origin checks x3', 'location.origin)' in g and 'e.origin !== location.origin' in h and 'e.origin !== GAME_ORIGIN' in g)
ck('manifest valid JSON', json.loads(open('FLUX-Sparta/public/manifest.webmanifest').read()) is not None)
ck('no duplicate backend', not os.path.exists('FLUX-Sparta/functions'))
print('\n--- Phase 2 baseline ---')
ck('dt clamp intact', 'Math.min(.032,(ts-last)/1000||.016)' in p)
# The count is not the invariant; "never inside a per-run function" is.
def _body(src,name):
    i=src.index('function '+name+'('); d=0; j=src.index('{',i)
    for k in range(j,len(src)):
        if src[k]=='{': d+=1
        elif src[k]=='}':
            d-=1
            if d==0: return src[i:k+1]
    return ''
_perrun=['newGame','endGame','registerMiss','resetFieldAfterMiss','offerRevive','setPaused']
_leaks=[f for f in _perrun if 'addEventListener(' in _body(p,f)]
ck('no listener registered inside any per-run function', not _leaks, ','.join(_leaks) or 'clean')
ck('17 listener sites, all one-shot (+visibilitychange/pageshow checkout resolver; D-38 banner adds 2, both once:true)', p.count('addEventListener(')==17 and "s.addEventListener('click', function(){ d.remove(); }, { once: true });" in p, str(p.count('addEventListener(')))
ck('single rAF chain', p.count('requestAnimationFrame(loop)')==2)
ck('misses++ one site', p.count('misses++')==1)
ck('registerMiss: 1 def + 1 call', p.count('function registerMiss')==1 and p.count('registerMiss();')==1)
ck('DIFFICULTY single source', p.count('const DIFFICULTY=')==1)
ck('level++ not a loop', p.count('level++;')==1)
print('\n--- D-01..D-15 ---')
ck('D-01 loop gated', 'if(window.__heroSuspended){ last=ts; requestAnimationFrame(loop); return; }' in h)
ck('D-01 intervals gated', h.count('if(window.__heroSuspended) return;')==2)
ck('D-01 no new rAF chain', h.count('requestAnimationFrame(loop)')==3)
ck('D-01 one message listener', h.count("addEventListener('message'")==1)
ck('D-01 suspend/resume wired', 'setHeroDemoSuspended(true)' in g and 'setHeroDemoSuspended(false)' in g)
# --- D-02 is now IMPLEMENTED, not removed ---
sw=open('FLUX-Sparta/public/sw.js',encoding='utf-8').read()
ck('D-02 service worker file exists', os.path.exists('FLUX-Sparta/public/sw.js'))
ck('D-02 registered by the game', "navigator.serviceWorker.register('/sw.js'" in p)
ck('D-02 claim is EARNED, not assumed', "id=\"offlineClaim\"" in p and "d.type!=='SW_READY'" in p)
ck('D-02 claim absent from static HTML', '>● OFFLINE READY' not in p)
ck('D-02 readiness handshake', "postMessage({type:'GET_READY'})" in p)
ck('D-02 registration absolute + scoped', "register('/sw.js', {scope:'/'})" in p)
_mf=json.loads(open('FLUX-Sparta/public/manifest.webmanifest').read())
ck('D-02 manifest start_url is the site root (Gateway)', _mf['start_url']=='/', _mf['start_url'])
ck('D-02 offline launch of start_url reaches the game', 'if (!isGameShell) return Response.redirect(GAME_ROOT, 302);' in sw)
ck('D-02 manifest scope declared', _mf.get('scope')=='/')
ck('D-02 shell stored under 3 keys', 'SHELL_KEY' in sw and 'SCOPE_ROOT' in sw and 'SHELL_URL' in sw)
ck('D-02 all cache keys absolute', "new URL('./', self.location).href" in sw)
ck('D-02 in-scope navigation fallback', 'inScope(url)' in sw)
ck('D-02 never resolves undefined', 'Offline copy not ready yet' in sw)
ck('D-11 resumes on any non-running state', "audioCtx.state !== 'running'" in p)
ck('D-11 gesture fallback present', "addEventListener('pointerdown', tryResumeAudio" in p)
ck('D-11 no suspended-only check left', "state==='suspended') audioCtx.resume()" not in p.split('function tryResumeAudio')[1][:400])
ck('D-02 cache version bumped to v4 (root move)', "CACHE_VERSION = 'flux-sparta-v4'" in sw)
ck('D-02 precache covers 7 assets', sw.count("new URL('./")>=6)
ck('D-02 API excluded from cache', "url.pathname.startsWith('/api/')" in sw)
ck('D-02 only 200 responses cached', 'response.status === 200' in sw)
ck('D-02 old caches deleted on activate', 'caches.delete(name)' in sw and 'name !== CACHE_VERSION' in sw)
ck('D-02 unrelated caches preserved', "name.indexOf(CACHE_PREFIX) === 0" in sw)
ck('D-02 clients claimed', 'clients.claim()' in sw)
ck('D-02 navigation network-first (no stale trap)', "req.mode === 'navigate'" in sw and 'fetch(req).then' in sw)
ck('D-02 offline navigation fallback', 'cache.match(SHELL_URL' in sw and 'cache.match(SHELL_KEY)' in sw)
ck('D-02 update path: SKIP_WAITING', "SKIP_WAITING" in sw and "SKIP_WAITING" in p)
# D-23 (RC2.8): `playing` alone let pauses and level holds through. The gate now
# waits on any part of a run.
ck('D-02/D-23 never swaps mid-run (pause, level hold, revive included)', 'if(playing || paused || runActive){ setTimeout(tryActivate,2000); return; }' in p)
ck('D-02 controllerchange reloads once', 'controllerchange' in p and 'reloading' in p)
ck('D-02 queue: retry on online event', "addEventListener('online'" in p)
ck('D-02 queue: whole run record', "id:playerId+':'+difficulty+':'+run.score+':'+run.level" in p)
ck('D-02 queue: permanent vs temporary split', "res.status===429||res.status>=500" in p)
ck('D-02 queue: attempts capped', 'SUBMIT_MAX_ATTEMPTS' in p)
ck('D-02 leaderboard reports need for connection', 'CONNECTION REQUIRED' in p)
ck('D-02 store reports need for connection', p.count('CONNECTION REQUIRED')==2)
ck('D-02 gameplay does not depend on SW', p.index("navigator.serviceWorker.register") > p.index('function newGame()'))
ck('D-05 one game constant, /play/ on this origin', g.count("window.FLUX_GAME_URL = window.location.origin + '/play/';")==1)
ck('D-05 one API-origin constant', g.count("window.FLUX_ORIGIN = window.location.origin;")==1)
_gcode=re.sub(r'/\*[\s\S]*?\*/','',g)
# ROOT MOVE: API and postMessage now use FLUX_ORIGIN; play navigation uses
# FLUX_GAME_URL. Counts verified by hand: 6 game-URL uses, 3 origin uses.
ck('D-05 6 game-URL uses (comments excluded)', _gcode.count('window.FLUX_GAME_URL')==6, str(_gcode.count('window.FLUX_GAME_URL')))
ck('D-05 3 origin uses (comments excluded)', _gcode.count('window.FLUX_ORIGIN')==3, str(_gcode.count('window.FLUX_ORIGIN')))
ck('D-05 static anchors valid', """href="'+window.FLUX_GAME_URL""" not in g.split('<script')[0])
ck('D-07 dead fn gone', 'playRealHeroAudio' not in g)
ck('D-08 flux-menu emitted x2', p.count("{type:'flux-menu'}")==2)
ck('D-08 gateway handles it', "t === 'flux-menu'" in g)
ck('D-09 record + migration', 'function bestRun()' in p and 'migrated:true' in p)
ck('D-09 matched pair sent', 'score:run.score' in p and 'level:run.level' in p)
ck('D-09 no swallowed failures', p.count('.catch(()=>{})')==0 and 'recordSubmitFailure' in p)
cfg=json.loads(re.sub(r'^\s*//.*$','',open('FLUX-Sparta/wrangler.jsonc').read(),flags=re.M))
ck('D-10 assets ./public', cfg['assets']['directory']=='./public')
ck('D-10 api routed', cfg['assets']['run_worker_first']==['/api/*'])
ck('D-10 config not published', not os.path.exists('FLUX-Sparta/public/wrangler.jsonc') and not os.path.exists('FLUX-Sparta/public/worker.js'))
for n in ['index.html','manifest.webmanifest','icon-192.png','icon-512.png','solar-inferno.webp','neon-tokyo.webp']:
    ck('D-10 asset kept: '+n, os.path.exists('FLUX-Sparta/public/'+n))
ck('D-11 visibilitychange', "addEventListener('visibilitychange'" in p)
ck('D-11 resumes existing ctx only', '!audioReady || !audioCtx' in p)
ck('D-12 overload gone', 'overload' not in p)
ck('D-14 stale comment gone', 'functions/api/submit-score.js' not in p)
ck('D-15 name reconciled', cfg['name']=='flux-sparta-3')
ck('D-13 orientation UNCHANGED (per instruction)', json.loads(open('FLUX-Sparta/public/manifest.webmanifest').read())['orientation']=='any')
print('\n--- D-16 FLUX ID (display only) ---')
_demo=open('FLUX-Sparta/public/hero-demo.html',encoding='utf-8').read()
ck('D-16 placeholder is FLUX ID', 'placeholder="FLUX ID"' in p)
ck('D-16 prompt is FLUX ID', "input.placeholder = 'ENTER FLUX ID'" in p)
ck('D-16 Gateway demo renamed', 'placeholder="FLUX ID"' in _demo)
ck('D-16 no visible CALLSIGN left', 'placeholder="CALLSIGN"' not in p+_demo and 'ENTER A CALLSIGN' not in p)
ck('D-16 element id UNCHANGED', '<input id="callsign"' in p)
ck('D-16 JS variable UNCHANGED', "callsign=localStorage.fluxCallsign" in p)
ck('D-16 storage key UNCHANGED', 'localStorage.fluxCallsign' in p)
ck('D-16 API field UNCHANGED (name:)', 'name:item.name' in p)
ck('D-16 no fluxId field invented', 'fluxId' not in p)
ck('D-16 PILOT terminology kept', "'PILOT'" in p)

print('\n--- D-17 / D-03 ---')
_gw=open('FLUX-Sparta/public/index.html',encoding='utf-8').read()
ck('D-17 greeting still present', 'id="welcomeRotator"' in _gw)
ck('D-17 all 9 languages kept', all(x in _gw for x in ['Welcome','Kumusta','Willkommen','Bem-vindo','Bienvenido','Bonjour']))
ck('D-17 Safari base rule untouched', '.welcomeRotator{position:absolute;top:max(78px,calc(env(safe-area-inset-top) + 68px))' in _gw)
ck('D-17 correction scoped to standalone', _gw.count('html.is-standalone .welcomeRotator{')==2)
ck('D-17 flag set before first paint', _gw.index("classList.add('is-standalone')") < _gw.index('</head>'))
ck('D-17 install detector unchanged', "return window.navigator.standalone === true || window.matchMedia('(display-mode: standalone)').matches;" in _gw)
ck('D-03 privacy page exists', os.path.exists('FLUX-Sparta/public/privacy.html'))
ck('D-03 terms page exists', os.path.exists('FLUX-Sparta/public/terms.html'))
ck('D-03 privacy link live', 'href="./privacy.html">Privacy Policy</a>' in _gw)
ck('D-03 terms link live', 'href="./terms.html">Terms</a>' in _gw)
ck('D-03 no legal link left as #', 'href="#">Privacy' not in _gw and 'href="#">Terms' not in _gw)
# D-03 RESOLVED (Sep 21, 2026): owner supplied the inputs. The guard flips --
# no placeholder may ever ship to players again.
_pv=open('FLUX-Sparta/public/privacy.html',encoding='utf-8').read(); _tm=open('FLUX-Sparta/public/terms.html',encoding='utf-8').read()
ck('D-03 no owner placeholder left in privacy', 'OWNER INPUT' not in _pv)
ck('D-03 no owner placeholder left in terms', 'OWNER INPUT' not in _tm)
ck('D-03 operator named', 'Jerome Tadaya' in _pv and 'Jerome Tadaya' in _tm)
ck('D-03 contact email present', 'playfluxofficial@gmail.com' in _pv and 'playfluxofficial@gmail.com' in _tm)
ck('D-03 effective date set', 'Effective date: <strong>September 21, 2026</strong>' in _pv and 'Effective date: <strong>September 21, 2026</strong>' in _tm)
ck('D-03 refund policy stated', 'within 14 days of your purchase' in _tm)
ck('D-03 age 13+, not directed to under-13', 'aged 13 and older' in _pv and 'at least 13 years old' in _tm)
ck('D-03 governing law set', 'State of California' in _tm and 'Alameda County' in _tm)

print('\n--- D-19 / D-20 ---')
ck('D-19 all four reveal elements', all(x in _gw for x in ['Flow \u00b7 Launch \u00b7 Unite \u00b7 Xcelerate','<div class="logo">FLUX</div>','THE WORLD HAS ENTERED THE FLUX.','100% FREE TO PLAY']))
_ph=re.sub(r'/\*[\s\S]*?\*/','', _gw[_gw.index('@media(max-width:700px){'):_gw.index('@media(max-width:700px){')+3000])
ck('D-19 phone suppression removed', 'animation:none' not in _ph.split('@media')[1] if '@media' in _ph else True)
ck('D-19 reveal animation still declared', 'body.anim .heroBrand{animation:heroBrandPulse var(--dur) ease-in-out infinite}' in _gw)
ck('D-19 compact phone sizing present', '.heroBrand .logo{font-size:min(10vw,44px)' in _gw)
ck('D-19 overlap still measured', 'brand.getBoundingClientRect()' in _gw and 'cta.getBoundingClientRect()' in _gw)
ck('D-19 reflow tiers present', 'heroBrand-t3' in _gw and 'heroBrand-t1' in _gw)
ck('D-19 measuring neutralises transform', 'body.heroBrand-measuring .heroBrand{transform:none!important' in _gw)
ck('D-19 suppression is last resort only', _gw.count("classList.add('heroBrand-unsafe')")==1)
ck('D-19 refits on orientation change', "orientationchange', function(){ setTimeout(fitHeroBrand, 300); }" in _gw)
ck('D-19 refits after fonts load', 'document.fonts.ready.then(fitHeroBrand)' in _gw)
ck('D-19 diagnostics gated', '/[?&]fluxdebug=1/.test(location.search)' in _gw)
ck('D-19 guard CSS intact', 'body.heroBrand-unsafe .heroBrand{animation:none!important}' in _gw)
ck('D-20 no timing changed (--dur:26s)', '--dur:26s' in _gw)
ck('D-19 demo untouched', '<iframe id="gameFrame" src="hero-demo.html"' in _gw)
ck('D-19 heroCTA untouched', '.heroCTA{position:absolute;left:0;right:0;bottom:calc(64px + env(safe-area-inset-bottom))' in _gw)
ck('D-18 still frozen (href="#" on install CTA)', 'id="getAppPlayBtn"' in _gw)

print('\n--- AUDIT-F01 / F02 / F03 guards ---')
_gwraw=open('FLUX-Sparta/public/index.html',encoding='utf-8').read()
_spraw=open('FLUX-Sparta/public/play/index.html',encoding='utf-8').read()
_strip=lambda t: re.sub(r'/\*[\s\S]*?\*/','',re.sub(r'^\s*//.*$','',t,flags=re.M))
_gs, _ss = _strip(_gwraw), _strip(_spraw)

# A. duplicate-definition guard
_d=len(re.findall(r'^\s*function submitScore\s*\(', _ss, re.M))
_a=len(re.findall(r'^\s*submitScore\s*=\s*(?:async\s+)?function', _ss, re.M))
ck('F02 exactly one submitScore definition', _d+_a==1, '%d decl + %d assign'%(_d,_a))
ck('F02 no patch assignment remains', _a==0)
ck('F02 canonical impl uses the queue', 'enqueueSubmission(item)' in _ss and 'flushSubmitQueue()' in _ss)
ck('F02 no fluxBestLevel_ in the submit path', 'fluxBestLevel_' not in _ss.split('function submitScore')[1][:400])

# C. initialization-order guard
_blocks=[(m.start(),m.end()) for m in re.finditer(r'<script\b[^>]*>.*?</script>', _gwraw, re.S)]
def _blk(idx):
    for i,(a,b) in enumerate(_blocks):
        if a<=idx<b: return i
    return -1
_assign=_gwraw.index('window.FLUX_ORIGIN =')           # the API origin is the F01 consumer now
_assign_game=_gwraw.index('window.FLUX_GAME_URL =')
_use=_gwraw.index('fetch(window.FLUX_ORIGIN')
_call=_gwraw.index('window.fetchGlobalGrid();')
ck('F01 constant assigned before its first consumer', _blk(_assign) < _blk(_use), 'block %d -> %d'%(_blk(_assign),_blk(_use)))
ck('F01 constant assigned before the auto-call', _blk(_assign) < _blk(_call))
ck('F01 assigned in the head block', _blk(_assign)==0)
ck('F01 exactly one assignment of each', _gs.count('window.FLUX_GAME_URL =')==1 and _gs.count('window.FLUX_ORIGIN =')==1)
ck('F01 game URL also assigned in the head block', _blk(_assign_game)==0)

# E. country parity guard
_sup=set(re.findall(r'<option value="([A-Z]{2})">', _spraw))
_meta=set(re.findall(r'\b([A-Z]{2}):\{flag:', _gwraw))
ck('F03 every Sparta country has Gateway metadata', _sup<=_meta, '%d missing'%len(_sup-_meta))
ck('F03 AE and QA both present and distinct', 'AE' in _meta and 'QA' in _meta)
ck('F03 unknown-code fallback retained', "{flag:'\U0001F30E',name:code||'Unknown'}" in _gwraw or 'name:code||' in _gwraw)

print('\n--- T-9 entitlement authority ---')
_sp=_strip(_spraw); _wk=open('FLUX-Sparta/worker.js',encoding='utf-8').read()
ck('T-9 no legacy-key ownership fallback', "return localStorage['fluxOwned_' + sku] === '1';" not in _sp)
ck('T-9 verified cache is versioned', "c.v !== 1" in _sp)
ck('T-9 verified cache checks provenance', "c.source !== 'server'" in _sp)
ck('T-9 verified cache is player-scoped', "c.playerId !== playerId" in _sp)
ck('T-9 reconciles stale paid keys', "localStorage.removeItem('fluxOwned_' + paidSku)" in _sp)
ck('T-9 reconciliation touches only paid skus', "['toxic', 'cosmic', 'solar'].forEach" in _sp)
ck('T-9 unlock uses server-confirmed sku', 'const confirmedSku = data.sku;' in _sp)
ck('T-9 unlock checks the session owner', 'confirmedFor === playerId' in _sp)
ck('T-9 checkout request is bounded', '15000' in _sp and 'ctl.abort()' in _sp)
ck('T-9 worker checks stripe mode', 'stripe_mode_mismatch' in _wk)
ck('T-9 worker verifies price reachable', 'price_not_found' in _wk)
ck('T-9 worker still requires payment_status paid', 'payment_status === "paid"' in _wk)
ck('T-9 no secret key echoed in responses', 'STRIPE_SECRET_KEY }' not in _wk.replace('Bearer ${env.STRIPE_SECRET_KEY}',''))

print('\n--- AUDIT-F06 installed-PWA checkout navigation ---')
ck('F06 Sparta validates the checkout URL', 'function isStripeCheckoutUrl(' in _sp)
ck('F06 Sparta detects being framed', 'function isFramed()' in _sp)
ck('F06 framed path posts upward', "type: 'flux-open-checkout'" in _sp)
ck('F06 not posted with wildcard origin', "'flux-open-checkout', url: url }, '*'" not in _sp)
ck('F06 top-level path still navigates directly', 'location.href = url;' in _sp)
ck('F06 Gateway validates actual playFrame sender', "var frame = document.getElementById('playFrame');" in _gs and "e.source !== frame.contentWindow" in _gs)
ck('F06 checkout must not authenticate hero gameFrame', "var frame = document.getElementById('gameFrame');" not in _gs[_gs.find("else if(t === 'flux-open-checkout')"):_gs.find("else if(t === 'flux-open-checkout')")+700])
ck('F06 Gateway validates the URL', 'isTrustedStripeCheckoutUrl(' in _gs)
ck('F06 hostname match, not substring', "\\.stripe\\.com$/.test(h)" in _gs and "h === 'checkout.stripe.com'" in _gs)
ck('F06 https required both sides', _gs.count("protocol !== 'https:'")==1 and _sp.count("protocol !== 'https:'")==1)
ck('F06 origin check still precedes everything', 'if(e.origin !== GAME_ORIGIN) return;' in _gs)
ck('F06 still one Gateway message listener', _gs.count("addEventListener('message'")==1)
ck('F06 entitlement authority unchanged', "c.source !== 'server'" in _sp)

print('\n--- RC2.5.5 single identity + purchase lock ---')
ck('Play navigates top-level', 'window.location.href = window.FLUX_GAME_URL;' in _gs)
ck('Play no longer iframes the game', 'frame.src = window.FLUX_GAME_URL' not in _gs)
ck('one FLUX_GAME_URL definition, same origin /play/', _gs.count("window.FLUX_GAME_URL = window.location.origin + '/play/';")==1)
ck('one place mints playerId', _sp.count('if(!localStorage.fluxPlayerId)')==1)
ck('purchase lock present', 'let purchaseInFlight = false;' in _sp)
ck('second purchase refused', 'if (purchaseInFlight) {' in _sp)
ck('lock cleared on error', 'purchaseInFlight = false;' in _sp)
ck('stuck button recoverable', 'resetBuyButton(btn, sku)' in _sp)
ck('handoff path reports itself', "return 'handoff';" in _sp)
ck('entitlement authority still server-gated', "c.source !== 'server'" in _sp)

print('\n--- RC2.5.6 MERGE: one origin, one identity ---')
import json as _j
_demo=open('FLUX-Sparta/public/hero-demo.html',encoding='utf-8').read()
_gm=_j.loads(open('FLUX-Sparta/public/manifest.webmanifest').read())   # ONE-APP: single manifest
_swt=open('FLUX-Sparta/public/sw.js',encoding='utf-8').read()
ck('MERGE Gateway served from the game origin', os.path.exists('FLUX-Sparta/public/index.html'))
ck('MERGE game URL is this origin /play/', "window.FLUX_GAME_URL = window.location.origin + '/play/';" in _gs)
ck('MERGE no other origin hardcoded (search/preview tags excepted)', 'flux-sparta-3.jeromevt72.workers.dev' not in _nometa(_gs))
ck('MERGE installed scope covers the game', _gm['scope']=='/')
ck('MERGE app opens on the Gateway at the root', _gm['start_url']=='/')
ck('MERGE no Play path opens a new tab', 'window.open(window.FLUX_GAME_URL' not in _gs)
ck('MERGE demo isolated from real storage', '__FLUX_DEMO_MODE__' in _demo and "Object.defineProperty(window, 'localStorage'" in _demo)
ck('MERGE demo cannot reach the API', "/\\/api\\//.test(u)" in _demo)
# The shim's comment mentions fluxPlayerId, so compare SCRIPT BLOCKS, not
# raw text: the isolation must be the very first script that executes.
_dblocks=re.findall(r'<script\b[^>]*>(.*?)</script>', _demo, re.S)
ck('MERGE isolation runs before any demo code', '__FLUX_DEMO_MODE__' in _dblocks[0] and 'fluxPlayerId' not in re.sub(r'/\*[\s\S]*?\*/','',_dblocks[0]))
ck('MERGE SW caches only the game shell', 'if (isGameShell && isCacheable(res))' in _swt)
ck('MERGE offline Gateway launch reaches the game', 'if (!isGameShell) return Response.redirect(GAME_ROOT, 302);' in _swt)
ck('MERGE old address redirects', os.path.exists('FLUX-Gateway-Redirect/_redirects'))

print('\n--- ONE-APP AUDIT ---')
_man=_j.loads(open('FLUX-Sparta/public/manifest.webmanifest').read())
ck('ONE manifest file', not os.path.exists('FLUX-Sparta/public/gateway-manifest.webmanifest'))
ck('ONE app id, stable', _man['id']=='/')
ck('app opens on the Gateway at the root', _man['start_url']=='/')
ck('scope covers Gateway and game', _man['scope']=='/')
ck('Gateway links the one manifest', '<link rel="manifest" href="/manifest.webmanifest">' in open('FLUX-Sparta/public/index.html',encoding='utf-8').read())
ck('demo declares no app identity', '<link rel="manifest"' not in _demo)
ck('Gateway registers the same root SW', "navigator.serviceWorker.register('/sw.js', { scope: '/' })" in _gs)
ck('demo isolation fails CLOSED', '__FLUX_DEMO_BLOCKED__' in _demo and 'window.stop()' in _demo)
ck('demo sealed from IndexedDB/Cache/XHR/beacon/SW/cookies',
   all(x in _demo for x in ["deny('indexedDB'","deny('caches'","deny('XMLHttpRequest'",'sendBeacon',"'serviceWorker'","'cookie'"]))
ck('app remembers its own pending checkout', 'rememberPendingCheckout(data.sessionId, sku);' in _sp)
ck('app resolves it on pageshow', "addEventListener('pageshow', function () { resumePendingCheckout(); });" in _sp)
ck('app resolves it on return to foreground', "if (!document.hidden) resumePendingCheckout();" in _sp)
ck('resolution never double-fires', 'handledSessions()' in _sp)
ck('pending record for another player ignored', 'p.playerId !== playerId) return null;' in _sp)
ck('return releases the purchase lock', "// Coming back from Stripe must never leave a purchase lock held.\n  purchaseInFlight = false;" in _spraw)
ck('no production Play path leaves the origin',
   'flux-gateway.jeromevt72' not in _gs and 'flux-sparta-3.jeromevt72' not in _nometa(_gs))
ck('old address is a redirect, not a copy of FLUX',
   not os.path.exists('FLUX-Gateway-Redirect/sw.js') and '<script' not in open('FLUX-Gateway-Redirect/index.html',encoding='utf-8').read()
   and not any(f.endswith('.webmanifest') for f in os.listdir('FLUX-Gateway-Redirect')))

print('\n--- ROOT MOVE: Gateway at "/", game at /play/ ---')
ck('ROOT Gateway is the site root page', os.path.exists('FLUX-Sparta/public/index.html') and 'heroPlayBtn' in _gwraw)
ck('ROOT game lives at /play/', os.path.exists('FLUX-Sparta/public/play/index.html') and 'function registerMiss' in _spraw)
ck('ROOT manifest start_url is "/"', _man['start_url']=='/')
ck('ROOT static PLAY anchors -> /play/', _gwraw.count('href="/play/" data-flux-play')==4)
ck('ROOT API never requested under /play/', '/play/api' not in _gs and 'FLUX_GAME_URL + \'/api' not in _gs)
ck('ROOT Stripe returns forwarded to the game', "window.location.replace(window.location.origin + '/play/' + q)" in _gwraw)
ck('ROOT forwarding only for Stripe params', "/[?&](session_id|checkout)=/.test(q)" in _gwraw)
ck('ROOT game links the one manifest absolutely', '<link rel="manifest" href="/manifest.webmanifest">' in _spraw)
ck('ROOT game icon absolute', '<link rel="apple-touch-icon" href="/icon-192.png">' in _spraw)
ck('ROOT SW game shell is /play/', "SHELL_URL  = new URL('./play/index.html', self.location)" in _swt)
ck('ROOT SW never treats "/" as the game', "SCOPE_ROOT," not in _swt.split('const PRECACHE')[1].split('];')[0])
ck('ROOT retired /welcome/ only forwards', '<link rel="manifest"' not in open('FLUX-Sparta/public/welcome/index.html',encoding='utf-8').read()
   and 'serviceWorker' not in open('FLUX-Sparta/public/welcome/index.html',encoding='utf-8').read())

print('\n--- STORE SWITCH (free-to-play launch) ---')
_spnow=open('FLUX-Sparta/public/play/index.html',encoding='utf-8').read()
ck('STORE store is CLOSED in the shipped build', _spnow.count('const STORE_OPEN = false;')==1 and 'const STORE_OPEN = true;' not in _spnow)
ck('STORE shop shows COMING SOON when closed', "(STORE_OPEN?s.price:'COMING SOON')" in _spnow)
ck('STORE closed shop has no BUY action', "else if(!STORE_OPEN){btn.textContent='SOON';btn.disabled=true;}" in _spnow)
ck('STORE live buySkin refuses before any request', _spnow.index('if (!STORE_OPEN) {') < _spnow.index("fetch('/api/create-checkout-session'", _spnow.index('buySkin = async function')))

print('\n--- AUDIT FIXES (A-1..A-4) ---')
_w=open('FLUX-Sparta/worker.js',encoding='utf-8').read()
_lbblk=_w[_w.index('async handleLeaderboard(url)'):_w.index('async handleSubmit(request)')]
ck('A-1 leaderboard rows carry a hash, not a playerId', 'pid: o.pid,' in _lbblk and 'playerId:' not in _lbblk.split('const top = ')[1].split('}));')[0])
ck('A-1 game highlights its row by hash', 'const mine=!!myPid && r.pid===myPid;' in _spnow and 'r.playerId===playerId' not in _spnow)
# RC2.8: EVERY admin function must itself start with the password check --
# checked one by one, so a function losing its guard cannot hide behind a count.
_admin_fns=re.findall(r'async function (admin\w+)\(request, env.*?\) \{\n(.*?)\n', _w)   # .*? so default params like (b) => ({}) still match
ck('A-2 every admin function checks the password first', len(_admin_fns)>=9 and all('requireAdmin(request, env)' in first for _,first in _admin_fns), str([n for n,f in _admin_fns if 'requireAdmin' not in f]))
ck('A-2 admin routes present', all(r in _w for r in ['/api/admin/find-player','/api/admin/remove-score','/api/admin/restrict','/api/admin/privacy-delete','/api/admin/purchases']))
ck('A-2 removal rebuilds country totals', 'await this.recomputeCountries();' in _w[_w.index('async handleAdminRemoveScore'):_w.index('async handleAdminRestrict')])
ck('A-2 admin page present, never touches player storage', os.path.exists('FLUX-Sparta/public/admin.html') and 'localStorage' not in open('FLUX-Sparta/public/admin.html',encoding='utf-8').read().split('<script>')[1])
ck('A-3 submitted names pass through cleanName', 'const name = cleanName(body.name);   // A-3' in _w)
ck('A-3 legacy names cleaned on the way out', 'name: cleanName(r.name),' in _w)
ck('A-4 server refuses checkout unless STORE_OPEN is "true"', 'if (String(env.STORE_OPEN || "").toLowerCase() !== "true") {' in _w)
ck('A-4 shipped wrangler has STORE_OPEN "false"', '"STORE_OPEN": "false"' in open('FLUX-Sparta/wrangler.jsonc').read())

print('\n--- RC2.8 (secondary source guards; runtime tests are the proof) ---')
_w8=open('FLUX-Sparta/worker.js',encoding='utf-8').read()
_g8=open('FLUX-Sparta/public/play/index.html',encoding='utf-8').read()
_a8=open('FLUX-Sparta/public/admin.html',encoding='utf-8').read()
_pv8=open('FLUX-Sparta/public/privacy.html',encoding='utf-8').read()
_wr8=open('FLUX-Sparta/wrangler.jsonc').read()
ck('D-22 per-difficulty bests', 'record.bests[difficulty] = { score, level, updatedAt: now }' in _w8)
ck('D-22 legacy records convert on load', 'function normaliseRecord(r, id)' in _w8)
ck('D-23 explicit run state set/cleared', 'playing=true; runActive=true;' in _g8 and 'playing=false; runActive=false;' in _g8)
ck('D-24 no give-up deletion for temporary failures', "recordSubmitFailure('gave_up')" not in _g8)
ck('D-24 single processor + mid-run rerun + yield', 'if(_flushing){ _flushAgain=true; return _flushing; }' in _g8 and 'await Promise.resolve();' in _g8)
ck('D-24 Retry-After honoured', "res.headers.get('Retry-After')" in _g8)
ck('D-25 countries rebuilt from records', 'async recomputeCountries()' in _w8 and 'applyCountryDelta' not in _w8)
ck('D-26 failed grant -> 500', 'if (!ok) return json({ error: "Delivery failed; retry" }, 500);' in _w8)
ck('D-26 grant is durable-first', 'await this.state.storage.put({ entitlements: nextEnt, seenSessions: nextSeen });\n    this.entitlements = nextEnt; this.seenSessions = nextSeen;' in _w8)
ck('D-26 reconciliation cron', 'async scheduled(event, env, ctx)' in _w8 and '"crons"' in _wr8)
ck('D-27 purchase lookup by email or pi_', 'customer_details[email]=' in _w8 and 'payment_intent=' in _w8)
ck('restricted players excluded publicly', 'if (await this.isRestricted(r.playerId)) continue;' in _w8)
ck('no mandatory review queue', 'REVIEW' not in _w8 and 'pending review' not in _g8.lower().replace('"pending review" is never shown','').replace("so \"pending review\"",''))
ck('admin: remove score and privacy delete are separate', "call('remove-score'" in _a8 and "call('privacy-delete'" in _a8)
ck('admin: privacy + purchases under Advanced', _a8.index('<details id="advanced">') < _a8.index('PURCHASE RECORDS'))
ck('privacy policy covers moderation records', 'Moderation records' in _pv8 and '90 days' in _pv8 and 'public tag' in _pv8)
ck('both store switches still closed', 'const STORE_OPEN = false;' in _g8 and '"STORE_OPEN": "false"' in _wr8)

print('\n--- RC2.8.1 (secondary source guards; runtime tests are the proof) ---')
_w9=open('FLUX-Sparta/worker.js',encoding='utf-8').read()
_g9=open('FLUX-Sparta/public/play/index.html',encoding='utf-8').read()
_pv9=open('FLUX-Sparta/public/privacy.html',encoding='utf-8').read()
_tm9=open('FLUX-Sparta/public/terms.html',encoding='utf-8').read()
_fz9=open('fuzz.mjs',encoding='utf-8').read()
ck('D-29 no ordinary spreads of server maps', '{ ...this.' not in _w9)
ck('D-29 maps loaded prototype-free', 'this.players = Object.create(null);' in _w9 and 'this.entitlements = NP(' in _w9)
ck('D-29 price lookup own-property only', 'Object.prototype.hasOwnProperty.call(priceMap, sku)' in _w9)
ck('D-30 fuzz exits nonzero on any issue', 'process.exit(issues.length ? 1 : 0);' in _fz9)
ck('D-30 release gate exists and fails on any suite', 'process.exit(failed.length ? 1 : 0);' in open('run-all-tests.mjs').read())
ck('D-31 verify-session reports delivery separately', 'pendingDelivery: true' in _w9 and 'const delivered = await grantEntitlement(' in _w9)
ck('D-31 game never claims completion while pending', "data.pendingDelivery === true" in _g9 and "data.delivered !== false" in _g9)
ck('D-32 no cross-device or cleared-data promise', not any(x in (_pv9+_tm9).lower() for x in ['across devices','follows you','another device using']))
# D-35 (RC2.8.2) replaced the D-32 "no recovery" statement with the restore
# code. The rule D-32 enforced is unchanged: policy, terms and shop say the
# SAME thing, and none of them promises more than the restore code delivers.
_rc35='The game menu shows a restore code for your pilot; entering that code in FLUX restores the pilot and the purchases linked to it'
ck('D-32/D-35 policy and terms carry the same recovery statement', _rc35 in _pv9 and _rc35 in _tm9 and 'If you lose both the restore code and your device data' in _pv9 and 'If you lose both the restore code and your device data' in _tm9 and 'FLUX does not currently provide account-based or cross-device purchase recovery' not in (_pv9+_tm9))
ck('D-32/D-35 store stays closed until recovery is device-tested', 'The store will remain closed until this recovery process has been tested on real devices.' in _pv9 and 'The store will remain closed until this recovery process has been tested on real devices.' in _tm9 and 'const STORE_OPEN = false;' in _g9)
ck('D-32/D-35 shop states the same recovery path', 'Save your restore code (EDIT' in _g9 and 'there is no cross-device recovery yet' not in _g9)
_rs35=open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'test-d35-restore.mjs'),encoding='utf-8').read()
ck('D-35 restore endpoint is POST-only and never cached', 'path === "/api/restore-check" && request.method === "POST"' in _w9 and 'headers.set("Cache-Control", "no-store");' in _w9)
ck('D-35 restore check reads prototype-free maps only', 'const rec = ownGet(this.players, playerId);' in _w9 and 'const owned = ownGet(this.entitlements, playerId);' in _w9)
ck('D-35 journal replay is the first code in the game script', _g9.index("localStorage.getItem('fluxRestoreJournal')") < _g9.index('const playerId=localStorage.fluxPlayerId'))
ck('D-35 restore replaces bests (no cross-pilot uploads)', "after['fluxBestRun_'+d]=null;" in _g9 and "playerId:id,at:now,restored:true" in _g9)
ck('D-35 restore refused during a run or purchase', "if(playing) return" in _g9 and "if(purchaseInFlight || pending)" in _g9)
ck('D-35 suite is in the release gate with its negative controls', "'test-d35-restore.mjs'" in open('run-all-tests.mjs').read() and "await control(" in _rs35)
_ad37=open('FLUX-Sparta/public/admin.html',encoding='utf-8').read()
ck('D-36 restore code is not in the main menu', 'id="restoreBtn"' not in _g9 and 'function syncRestoreLink()' in _g9)
ck('D-36 game over sets the Mode label', "document.getElementById('finalMode').textContent=String(difficulty).toUpperCase();" in _g9)
ck('D-37 issue-restore requires the admin password and a reason', 'async function adminIssueRestore(request, env) {\n  const denied = requireAdmin(request, env); if (denied) return denied;' in _w9 and 'if (reason.length < RESTORE_REASON_MIN)' in _w9)
ck('D-37 log is written before a code is returned', _w9.index('try { await this.state.storage.put({ restoreLog: next }); }') < _w9.index('return json({ ok: true, code: await restoreCodeFor(id), tag, name });'))
ck('D-37 admin page asks how the player was verified', 'How did you verify them?' in _ad37)
ck('D-36 confirm screen names the SAVED pilot (EDIT clears the in-memory flag)', 'restorePilotLabel(savedName,curTag' in _g9 and 'profileComplete?callsign' not in _g9)
ck('D-36/37 suite is in the release gate', "'test-d36-d37.mjs'" in open('run-all-tests.mjs').read())
_gw38=open('FLUX-Sparta/public/index.html',encoding='utf-8').read()
ck('D-38 robots.txt and sitemap.xml exist with full addresses', os.path.exists('FLUX-Sparta/public/robots.txt') and 'https://flux-sparta-3.jeromevt72.workers.dev/play/' in open('FLUX-Sparta/public/sitemap.xml').read())
ck('D-38 in-app banner on both pages, never touches identity', 'IN-APP BROWSER BANNER' in _gw38 and 'IN-APP BROWSER BANNER' in _g9)
ck('D-38 suite is in the release gate', "'test-d38.mjs'" in open('run-all-tests.mjs').read())
ck('D-39 an empty name no longer blocks the first run', "if (!profileComplete && document.getElementById('callsign').value.trim())" in _g9 and 'function uploadOrAskName()' in _g9)
ck('D-39 unnamed pilots never upload (D-16 kept)', "uploadOrAskName();   // D-39" in _g9 and "if(profileComplete) submitScore();" in _g9 and "input.placeholder = 'ENTER FLUX ID'" in _g9)
ck('D-40 first-run color hint, never blocks input', 'function showColorHint()' in _g9 and 'pointer-events:none' in _g9)
ck('D-41 level cap matches the game (9)', 'const MAX_LEVEL = 9;' in _w9)
ck('D-42 no "every run counts" claims on the Gateway', all(x not in _gw38 for x in ['Every run counts','Every legitimate run','Real totals from every FLUX run','Every game you play adds']))
_hd45=open('FLUX-Sparta/public/hero-demo.html',encoding='utf-8').read()
ck('D-43 new pilots get a visible PILOT-XXXX name, never silent PLAYER', "callsign = 'PILOT-' + t;" in _g9 and "localStorage.fluxAutoName = '1';" in _g9)
ck('D-44 only brand-new pilots start on Easy', "if (!localStorage.fluxDifficulty) { difficulty = 'easy';" in _g9)
ck('D-45 roundRect stand-in in the game and the Gateway preview', 'CanvasRenderingContext2D.prototype.roundRect = function' in _g9 and 'CanvasRenderingContext2D.prototype.roundRect = function' in _hd45)
ck('D-45 game loop schedules the next frame first', 'requestAnimationFrame(loop);   // D-45' in _g9)
ck('RC2.8.5 the start button has exactly one handler', _g9.count("getElementById('startBtn').onclick")==1)
ck('D-46 lite graphics: remembered flag, non-Retina, glow off, fewer particles', "window.__fluxLite = (function(){" in _g9 and "dpr=window.__fluxLite?1:" in _g9 and "Object.defineProperty(ctx, 'shadowBlur'" in _g9)
ck('D-46 lite also calms the moving background layers', '.fluxLite #nebulaDrift{display:none!important}' in _g9)
ck('D-47 Gateway PLAY no longer shows the install screen first', 'showPlayChoice();\n      return;' not in _gw38)
ck('D-48 install offered only after a first game', "if (fluxIsStandalone() || !fluxHasPlayed()) return null;" in _g9)
ck('D-49 bring-my-pilot uses the tested restore flow', "openRestoreConfirm(parsed.playerId, r.info);" in _g9)
ck('RC2.8.6 suite is in the release gate', "'test-rc286.mjs'" in open('run-all-tests.mjs').read())
ck('RC2.8.5 suite is in the release gate', "'test-rc285.mjs'" in open('run-all-tests.mjs').read())
ck('D-33 one global tag map', 'async tagMap()' in _w9 and 'this.tagCache = map;' in _w9)
ck('D-33 leader playerId never leaves the server', 'for (const { leaderId, leaderPid, topTag, ...c } of Object.values(this.countries))' in _w9)
ck('D-34 reconciliation paginates', 'starting_after=' in _w9 and 'page.has_more' in _w9)
ck('D-34 reconciliation window documented', 'const RECONCILE_WINDOW_SEC = 72 * 3600;' in _w9)
ck('both store switches still closed', 'const STORE_OPEN = false;' in _g9 and '"STORE_OPEN": "false"' in open('FLUX-Sparta/wrangler.jsonc').read())

print('\n'+'='*52)
print(('  %d FAILED: %s'%(len(F),', '.join(F))) if F else '  ALL REGRESSION CHECKS PASSED')
print('='*52)
sys.exit(1 if F else 0)
